task: 'image_fitting'

data:
  path: ./data/image_fitting/fox.png

iterations: 100

optimizer:
  name: 'CG'
  lr: 0.001
  max_iter: 10
  history_size: 10
  line_search_fn: "strong_wolfe"


MLP:
  width: [256,32,3]
  act: 'relu'
  dropout: 0
  loss_fn: 'MSE'

KAN:
  width: [256,16,3]
  grid: 5
  k: 3
  loss_fn: 'MSE'
