wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711477491.0
    t:
      1:
      - 55
      - 105
      2:
      - 55
      - 105
      3:
      - 2
      - 13
      - 18
      - 23
      - 37
      4: 3.10.12
      5: 0.16.5
      8:
      - 5
      13: darwin-x86_64
num_eqs:
  desc: null
  value: 20
num_vars:
  desc: null
  value: 30
sigma:
  desc: null
  value: 0.95
