wandb_version: 1

vis:
  desc: null
  value: true
num_vars:
  desc: null
  value: 30
num_eqs:
  desc: null
  value: 10
tol:
  desc: null
  value: 0.01
max_iter:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711477009.0
    t:
      1:
      - 55
      - 105
      2:
      - 55
      - 105
      3:
      - 2
      - 16
      - 23
      4: 3.10.12
      5: 0.16.5
      8:
      - 5
      13: darwin-x86_64
